spring:
  application:
    name: movieflix
  datasource:
    url: jdbc:postgresql://localhost:5433/movieflix #estï¿½ com 5433 devido a um conflito com o postgres instalado na maquina.
    username: postgres
    password: postgres

  jpa:
    show-sql: true

  flyway:
    enabled: true


movieflix:
  security:
    secret: "senhaMisteriosa"